sudo: false

language: cpp

os:
  - osx

compiler:
  - clang
#  - gcc

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

before_install:
  - brew update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - brew unlink boost

script:
  - brew install --verbose --build-bottle boost --c++11
  - brew bottle boost

before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - "echo 'Deploying files to Github: '$RELEASE_FILES"

deploy:
  provider: releases
  api_key:
    secure: gBAu4io/527XhuLgWGFw0oOmIwItdHUPyEa9pLMNx+H9BWEbIAEWnc7GmI1FYxxdiSXPoXelKjtjVCVBwQJL1Tcad0muIr6h83FLKv5iN6CVj3O3uJxrcDzOjSdc929lZg7p6lrH9+zvU2C+RS7UZZqomsY/NVJ5zj70sFLnWVIC+gs5QcJJmci1QAD2jdUm7iErO1ve211strmFsCrLzZmhSCujaBU3kM3FgSC8ID/Bw/+sLfr6hIn4EJYlp2tazd2vrARRWAoOBuKj2YCzvJS4ID1Z7DV3F+iaRShgnJN034GT22O/lmlPYK+jU2S7kZGnEz9MA12QRMKeR5gVT1gh9AAh8iZS9KPjXTWrnXW5ngckBMZo7Z0UI+gSCj8CWsstaShvc53y2yCU9eeTz8zjRPPqrAhOMxrCerENob18SFvJElHx48WlgTVOfwFHlalewLNUPibBH0lV2T01WsxVusc/9t/yHOsO2wUrD7+HccU9+R2P2197S/ShT2/IORvHO2lTnrheowMnhgKpT1LQEeFb7WtVcRSnqlZJf+6CWMup3p9dAd3XcQTIWKZcE6OG0I9s7I129h586o9EBnS2mRXQ836oA0EGScvZbNgvB4sUdoa1PxTqMO6KZoH2QOMpyxljuFquifBY5uYNN2Czx9PwLPaYb2HDPL4Bito=
  file: "${RELEASE_FILES}"
  skip_cleanup: true
  on:
    repo: Malvineous/travis-homebrew-bottle
  overwrite: true
